### ISSUE TITLE
Problem running Standalone example

### ISSUE THREAD

**Issue by 10k10** [ericstoneking/42#100]
Hey!

I'm trying to run ./42 Standalone example and it returns the following error: **SC[0].Whl[1] Node out of range**. I didn't modify any example's files. I can run Demo and other examples without problem.

**Comment by ericstoneking** [comment]
Thanks for the bug report.  I recently refactored nodes and some other things, and the wheel sections in SC_CfsSat0.txt and SC_CfsSat1.txt weren't fully updated properly.  I've committed corrected versions.

**Comment by 10k10** [comment]
Thanks for the quick support! It's now running as expected.

**Comment by 10k10** [comment]
Thanks for the quick support! It's now running as expected.
