### ISSUE TITLE
42: command not found

### ISSUE THREAD

**Issue by vvishish** [ericstoneking/42#101]
Hi, I am using Ubuntu and have successfully compiled 42. But when I try to run the 42 command with an argument, the error shows 42: command not found.

**Comment by haisamido** [comment]
did you try **./**42 ?

**Comment by vvishish** [comment]
Tried both

**Comment by haisamido** [comment]
what does your pwd show and where did you compile code?

**Comment by vvishish** [comment]
The 42 directory which is on the Desktop

**Comment by vvishish** [comment]
I think I got it, shouldn't have done it on the Desktop.! xD It's working now. Thanks @haisamido
