### ISSUE TITLE
Attitude variables and DCM

### ISSUE THREAD

**Issue by 10k10** [ericstoneking/42#104]
Hey Eric!

I'm using 42 to develope my attitude determination algorithm and I'm confuse about some output variables.

1. Are RPY.42 the angles of the SC wrt inertia? The same angles used in DCM? If yes, it will correspond to "SC[0].B[0].qn", right?
2. Is it possible to get the cossine matrix output? I tried to add "SC[0].B[0].CN" in my IPC configurator but didn't work.

Thanks for your help.

Robinson.

**Comment by ericstoneking** [comment]
Hi Robinson,

1)  RPY are Euler angles with respect to local vertical-local horizontal.  Look in Source/42report.c to see how they are computed.

2)  Sure.  Look in Source/42report.c to see how qbn.42 is generated, and use that as your guide.

Regards,
-Eric (he/him)
