### ISSUE TITLE
Sim Duration and Step Size

### ISSUE THREAD

**Issue by annamaskolenko** [ericstoneking/42#106]
Hello Eric,

What is the limit for simulation time? I have set simulation duration to 100000s, but the simulation automatically terminates approx. at 50000s. I am wondering if you know what the problem might be.
Also, is it possible to set step size to say 1.0s instead of 0.1s. When I do that the error ''Error:  FswSampleTime smaller than DTSIM.\n'' comes out.

Thank you in advance,
Anna

**Comment by ericstoneking** [comment]
Hi Anna,

I know some folks have run year-long sims.  I personally have exceeded 100,000 sec.  I don't know why yours might be bailing out at 50,000.

You certainly can set the sim timestep to 1.0 sec.  You will also want to set your FswSampleTime (in your SC*.txt file, near the top) to something equal to or greater than the sim timestep.  Same for any sensor sample times you have defined.

Regards,
-Eric (he/him)
