### ISSUE TITLE
MTB Models  and R frame.

### ISSUE THREAD

**Issue by httung0701** [ericstoneking/42#110]
Hi
I'm new to this field. I have some questions, please help me out.
1.As far as I know, AC->MTB[i].Mcmd is sent from an external application to 42. how can i determine it assuming that i'm using socket to communicate cFS with 42.
2. what is the Mcm? is it wanted moment?
3. what ís r frame in the command file, i am confused about it when i run simulation using cmd : 0.0 SC[0] qrn = [0.0  0.0  0.0  1.0]
after a while, the B axis ís aligned with N asix, i gues r frame is Body frame.
Thank you.

**Comment by ericstoneking** [comment]
1)  If you're using a socket, you should be able to monitor socket traffic by setting "Echo to stdout" TRUE in your Inp_IPC.txt.
2)  Yes, Mcmd is the desired magnetic moment, in A-m^2.
3)  R is the command frame, i.e. where you *want* B to be.  qrn  = [0 0 0 1] means, align R  with N.  After a while, the controller makes B align with R  (which incidentally aligns it with N).  To check this, make qrn be something else, like [0.5 0.5  0.5 0.5], and  watch what B does.

**Comment by httung0701** [comment]
Thanks you so much for your quickly response. I see nowhere that AC->MTB[i].Mcmd is defined or decleared in source code. Can you help me with that.
Another thing is when i set 2 prefixes in inp_cmd  with one is " Orb" and the other is "World". Besides information about two prefixes, those lines keep being inserted through the screen cyclically :
SC[0].AC.svb = 1.000000000000e+00 0.000000000000e+00 0.000000000000e+00
SC[0].AC.bvb = 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00
SC[0].AC.Hvb = 4.785756503063e-317 -4.785756503063e-317 4.785756503063e-317
SC[0].AC.G[0].Cmd.Ang = 1.570796326795e+00 0.000000000000e+00 0.000000000000e+00.
Can you tell me the reason? I've been finding out about it for a while.

**Comment by ericstoneking** [comment]
AC->MTB[i].Mcmd is declared in Include/AcTypes.h.

You don't give me enough information to see why the AC variables are getting sent.  If you don't mind, attach your Inp_IPC.txt.

**Comment by httung0701** [comment]
<<<<<<<<<<<<<<< 42: InterProcess Comm Configuration File >>>>>>>>>>>>>>>>
1                                       ! Number of Sockets
**********************************  IPC 0   *****************************
ACS                                     ! IPC Mode (OFF,TX,RX,TXRX,ACS,WRITEFILE,READFILE)
0                                       ! AC.ID for ACS mode
"State00.42"                            ! File name for WRITE or READ
CLIENT                                  ! Socket Role (SERVER,CLIENT,GMSEC_CLIENT)
localhost     10001                     ! Server Host Name, Port 
TRUE                                    ! Allow Blocking (i.e. wait on RX)
TRUE                                    ! Echo to stdout
2                                       ! Number of TX prefixes
"SC"                                    ! Prefix 0
"Orb"                                   ! Prefix 1
**********************************  IPC 1   *****************************
OFF                                     ! IPC Mode (OFF,TX,RX,TXRX,ACS,WRITEFILE,READFILE)
0                                       ! AC.ID for ACS mode
"State01.42"                            ! File name for WRITE or READ
CLIENT                                  ! Socket Role (SERVER,CLIENT,GMSEC_CLIENT)
localhost     10002                     ! Server Host Name, Port 
TRUE                                    ! Allow Blocking (i.e. wait on RX)
FALSE                                   ! Echo to stdout
1                                       ! Number of TX prefixes
"SC[0].AC"                              ! Prefix 0
**********************************  IPC 2   *****************************
OFF                                     ! IPC Mode (OFF,TX,RX,TXRX,ACS,WRITEFILE,READFILE)
1                                       ! AC.ID for ACS mode
"State02.42"                            ! File name for WRITE or READ
CLIENT                                  ! Socket Role (SERVER,CLIENT,GMSEC_CLIENT)
localhost     10003                     ! Server Host Name, Port 
TRUE                                    ! Allow Blocking (i.e. wait on RX)
FALSE                                   ! Echo to stdout
1                                       ! Number of TX prefixes
"SC[1].AC"                              ! Prefix 0
**********************************  IPC 3   *****************************
OFF                                     ! IPC Mode (OFF,TX,RX,TXRX,ACS,WRITEFILE,READFILE)
0                                       ! AC.ID for ACS mode
"State03.42"                            ! File name for WRITE or READ
CLIENT                                  ! Socket Role (SERVER,CLIENT,GMSEC_CLIENT)
localhost     10004                     ! Server Host Name, Port 
TRUE                                    ! Allow Blocking (i.e. wait on RX)
FALSE                                   ! Echo to stdout
1                                       ! Number of TX prefixes
"SC[0].Tach[0]"                         ! Prefix 0
Once again, you save my day !!

**Comment by httung0701** [comment]
[Inp_IPC.txt](https://github.com/ericstoneking/42/files/10963526/Inp_IPC.txt)
here it is. Once again, you save my day.

**Comment by ericstoneking** [comment]
That helps.  The AC variables are being sent by the external process (is it AcApp?) back to 42.  

If you want to change what variables are being sent, you have two options.

The long-term solution is to read Database/Readme.txt.  The code that reads and writes to sockets is autogenerated C code.  This C code is written by some python scripts, using annotations is the header files (i.e. AcTypes.h).

If you don't want to get into that process, you can edit Source/IPC/AppWriteToSocket.c yourself.  If that gets tedious, then you'll understand why I went with autogeneration :-)

Happy coding,
-Eric
