### ISSUE TITLE
Initial command to send data over TCP/IP

### ISSUE THREAD

**Issue by 10k10** [ericstoneking/42#112]
Hi,

Maybe a dumb question but I couldn't solve. I've tested 42 as TCP CLIENT and it works very well, when I connect to the server it sends all data specified in Inp_IPC.txt.

Now I'm trying to use in SERVER mode, but when I open the connection there's no data comming. This issue make me think that there's some command to send to the server to gets the data back. So, what is wrong?

Thanks for help.

**Comment by ericstoneking** [comment]
Hi,

The Tx/Rx example might be useful for debugging this.  See "Docs/TxRx Example.txt".  The Tx end is the server, so you start it first.  Watch the messages it writes to the terminal.  Something like:

   Server is listening on port 10001

Then when you run 42 Rx, you'll see this on the Rx end:
    Client connecting to Server on Port 10001
    Client side of socket established.

and on the Tx end:
    Server side of socket established.

And then a flood of socket traffic.

So, is your socket getting established in the first place?

If you get one message from your server, then it stalls, then it's probably waiting for an acknowledgment message from your client.

That's all I can guess based on available information.

Regards,
-Eric
