### ISSUE TITLE
additional docs or training for socket comms in 42

### ISSUE THREAD

**Issue by khavernathy** [ericstoneking/42#148]
Hi, I'd like to know if there are any other resources (other than Docs in the repo here), for example videos or tutorials that can be shared for 42.

It'd be especially helpful if there is any content on running the Tx/Rx features for setting up a real-time simulator with real hardware inputs.

**Comment by ericstoneking** [comment]
Hi Doug,

To answer your first question, I'm not aware of any other training resources out there.

You have, I'm sure, run the TxRx and Standalone example problems, right?  Once you've done that, if you still don't see your way forward, come back and I'll try to get you pointed in the right direction.

Regards,
-Eric (he/him)

**Comment by ericstoneking** [comment]
Hi Doug,

Good, then you're almost there.  I wouldn't suggest using READFILE, RX will work better for you.  Let 42 be the Rx end of the socket.  Your external app needs to take the place of the Tx end of the socket.  (Which end is the server and which is the client is up to you; 42 can do either.)  Your app needs to send messages over the socket that look like this:

TIME 2014-172-00:00:04.500000000
SC[0].B[0].wn = -1.748865083681e-03 -6.927475621347e-03 2.421122225958e-03
SC[0].B[0].qn = 4.985869992252e-01 2.909902747759e-01 6.853904088098e-02 8.136572153337e-01
[EOF]

wn are your angular rates, qn is your attitude.  

In Inp_IPC.txt, set "Allow Blocking" to FALSE, so 42 won't wait for messages from your app.  It will carry on as a normal sim, overwriting wn and qn when they come in from your app.

I think that should do it.  Let me know if it doesn't.

Regards,
-Eric (he/him)

**Comment by ericstoneking** [comment]
Hi Doug,

42 uses TCP, which (if I understand right) guarantees that packets get delivered intact and in order (the other option would be UDP, which is fire-and-forget).  The messages you send are in plain text (inefficient I know, but easy to check).  If you're coding in C, you can crib from 42/Kit/Source/iokit.c to initialize your socket, and study 42/Source/IPC/AppWriteToSocket.c to see how one amateur builds and sends a message.

I know that Matlab, Julia, and the Godot game engine all have socket functionality.  I assume it's pretty common.  But I'm a dynamicist, not a network guru, so you're on your own to figure that part out. ;-)

Good luck,
-Eric (he/him)

**Comment by dmccomas** [comment]
OpenSatkit (OSK) has an app called i42 (42 interface)
https://github.com/OpenSatKit/OpenSatKit/tree/master/cfs/apps/i42  that may
be helpful. This app reads sensor data from 42 and sends actuator commands.

I'm rehosting the OSK 42 apps to cFS Basecamp (BC42_INTF and BC42_CTRL)
https://github.com/orgs/cfs-apps/repositories but it's still in progress.
The goal is to have a Basecamp project that demonstrates how to interface
the cFS with 42.

Basecamp is part of a larger educational effort called Space Steps
https://spacesteps.com/ . My partner Bill and I would love feedback on what
type of educational material would be beneficial.

Take care,
- Dave
