### ISSUE TITLE
Magnetic Moment of a Satellite and Hysteresis Rods Inclusion

### ISSUE THREAD

**Issue by Quatorze14** [ericstoneking/42#18]
Hi M. Stoneking,

We are using 42 in our project to simulate the current design of a CubeSat. As of right now, we are concerned with the inclusion of the magnetic moment created by permanent magnets required for our payload to work. We tried to use magnetorquer as a permanent magnet but we can't seem to find any direct control of them. Is there a way to include the magnetic moment from the satellite itself or to directly control the magnetorquer?

We also want to know if it is possible to add the effect of hysteresis rods to the simulation as this would better reflect our current attitude control configuration.

Thank you
Julien Roy

**Comment by ericstoneking** [comment]
Hi Julien,

You are on the right path using the magnetorquer model.  Look for the function 42actuators.c:MTBModel to see how torques are derived from magnetic moments.  You just need to provide your desired magnetic moment along with the other parameters.  There are various ways to do this for your purposes, either populating the variable SC[i].AC.MTB[j].Mcmd (with i and j as appropriate), or setting up more calls to MTBModel customized to your situation.  Go for it.

You'll have to write your own hysteresis rod model, but studying MTBModel will show you where to plug it in.

If you haven't already, I'll also suggest you familiarize yourself with the MTBType struct in Include/42types.h.

Regards,
-Eric
