### ISSUE TITLE
42 Installation Packages

### ISSUE THREAD

**Issue by acxz** [ericstoneking/42#2]
Hello Eric, I'd like to preface this by saying you have created a wonderful project with very strong capabilities. 42 has been and is being used widely at my uni (and many other places I'm sure) and I hope it continues to do so.

I would love to see 42 being used widely. As such, I think it would be a great idea to create packages for this software. Things like a Debian package, Ubuntu PPA, macOS homebrew, etc. Having packages will simplify the installation process and the original hurdle of accessing the software. Are there any plans for creating packages for this project? 

I understand that some installation instructions are available in the docs, but it would be great if these instructions were explicitly listed out somewhere like the project wiki instead of inside the repo.

**Comment by ericstoneking** [comment]
Hi acxz,

Thanks for the kind words.  I appreciate your enthusiasm.

I have no plans to create distribution packages.  If you (or anybody) would like to do so, go for it!

Same thing goes for the wiki.  It's not a priority for me, but if the community wants it, by all means do it.

Regards,
-Eric
