### ISSUE TITLE
Document Clarification: Pointing Target Commands from Network Port

### ISSUE THREAD

**Issue by atk5025** [ericstoneking/42#24]
I see clearly that the intended break for the network interface is between sensor measurements and actuator drives. My application I would like to connect cFS to send commands to the standalone 42 application, emulating a communications bus with a stand alone ACS system. 

For this, I'm anticipating sending commands that sent the spacecraft to various pointing states. 

I see the Inp_CMD file but it doesn't provide an obvious way for those commands to be augmented by another service.

E.g. initial command
0.0 SC[0] qrl = [0.0 0.0 0.0 1.0]

42 Receive via the network 
SC[0] qrl = [0.0 1.0 0.0 0.0] (I have not validated this new command but should get the point across)

Is this supported?

**Comment by ericstoneking** [comment]
Sensor info is the most obvious thing to pass from 42 to AcApp over the socket, but you can add to that fairly easily.  Get familiar with what [~>~] means.  Then look in AcTypes.h for the Cmd struct.  If you don't see your way forward from there, come back.
