### ISSUE TITLE
Pseudo code for 42

### ISSUE THREAD

**Issue by AKiwi69** [ericstoneking/42#29]
This is not an issue but a question.  We use this program at my university's small satellite program for our two 6u cubesats.  The department wants me to go line by line and write what each part of the code does in simple terms so someone new to it can learn it fairly quickly.  Do you have a pseudo code already written for this program?

**Comment by ericstoneking** [comment]
Pseudocode, no.  It goes without saying that your audience will have read the Readme and browsed the docs, of course.  If you need to walk through it line by line, then I would suggest starting with 42exec.c:SimStep, and working from the top layer down.  I'd focus on the code that your audience will be more likely to interact with and modify: 42perturb.c, 42sensors.c, 42fsw.c, and 42actuators.c.  I'd save 42dynamics.c and 42GlutGui.c for last.

Good luck with your task.
