### ISSUE TITLE
Rotation problem

### ISSUE THREAD

**Issue by vladtcvs** [ericstoneking/42#55]
When L3 on unit sphere viewer touches to the top of the window, rotation in lvlh frame stops - sc always directed to earth

But in default demo config SC don't have any thrusters or wheels

![image](https://user-images.githubusercontent.com/3390973/111824221-f80f0b80-88f6-11eb-9dea-bb3440198c87.png)

**Comment by vladtcvs** [comment]
It turned out that by default SC has ideal actuators..

**Comment by annamaskolenko** [comment]
What flight software (FSW) is your SC using? And have you sent any commands to the spacecraft? I cannot manage to align the SC with L-frame
