### ISSUE TITLE
Use UTC.JulDay (UT1, actually) for JD2GMST

### ISSUE THREAD

**Issue by nsthyshin** [ericstoneking/42#64]
Hi, I'm one of your users from South Korea.
First of all, I'm sincerely thankful for your code. It helped my project a lot, really.
Actually, I've noticed you mentioned that the function JD2GMST us JD in TT as its input.
After I looked through your reference and others, however, it has to be UT1 time system, not TT.
Could you check again about this matter?

Best regards,
Jinyoung

**Comment by ericstoneking** [comment]
Hi Jinyoung,

I'm glad you like it.

You are correct.  JD2GMST should take UT as its input, not TT.  I've made the correction in my code; it will be in my next upload, whenever that is.

I acknowledge the distinction between UTC and UT1, but it's not something I want to bookkeep.  You're free to manage that in your local copy, of course :-)

Regards,
-Eric (he/him)
