### ISSUE TITLE
Unused but set variable warnings

### ISSUE THREAD

**Issue by acxz** [ericstoneking/42#7]
GCC: 8.3
Command: `make`
@ericstoneking I am getting several `-Wunused-but-set-variable` warnings. Is there a particular reason for keeping them? Would it be fine if I submit a PR that resolves these warnings?

**Comment by ericstoneking** [comment]
Hi,

42 is under continual development.  There are usually loose ends here and there.  If these bother you, feel free to comment them out or remove them.  My apologies for the lack of polish.
