### ISSUE TITLE
Documentation for Inp_Graphics.txt file parameters ?

### ISSUE THREAD

**Issue by GateraGael** [ericstoneking/42#71]
Hello all, I tried to find the documentation for the different options available for the "Initial POV View" field in the "Inp_Graphics.txt".
Which other options except FRONT and FRONT_RIGHT are there ? I tried to use "BACK" but it returned a Bogus input.

**Comment by ericstoneking** [comment]
Hi Gael,

Look in Source/42init.c:DecodeString, where the keywords get turned into macro values.

I should add, that setting only has an effect when the POV Mode is FIXED_IN_HOST.

Regards,
-Eric

**Comment by GateraGael** [comment]
@ericstoneking is there a better place to ask general debugging questions as opposed to actual issues in the code itself?
