### ISSUE TITLE
Attempted divide by zero in UNITV (Line 337 of mathkit.c - NaN Centroid in SurfaceForceProps

### ISSUE THREAD

**Issue by GateraGael** [ericstoneking/42#72]
Hello, I followed all the steps in the "A Process to Easily Create .obj Mesh Files for 42 from Your existing CAD Files" pdf document.
Also, I made sure that the origin of my model in Wings3D is also the origin of my imported body in Wings3D as pointed out at the top of page 8 but got that error.

Full Output ---
Attempted divide by zero in UNITV (Line 337 of mathkit.c)
Attempted divide by zero in UNITV (Line 337 of mathkit.c)
Attempted divide by zero in UNITV (Line 337 of mathkit.c)
Attempted divide by zero in UNITV (Line 337 of mathkit.c)
NaN Centroid in SurfaceForceProps

**Comment by ericstoneking** [comment]
Looks like a zero-area poly snuck through.  This is a great time to get to know your debugger.  Figure out which poly is triggering the "NaN Centroid" error.  SurfaceForceProps is in Kit/Source/geomkit.c.  Happy hunting.
