### ISSUE TITLE
Demo Crash

### ISSUE THREAD

**Issue by annamaskolenko** [ericstoneking/42#94]
Hello Eric
I do apologise for asking so many questions, but I am still learning how to use 42.
My issue is that when I try to run Demo folder with Cmd_Demo script file, simulation launches but then immediately crashes after saying Bogus Euler Sequence 0 in A2C in the command prompt app
How can I fix that?

**Comment by ericstoneking** [comment]
Hi,

This is a classic.  One of your input files has been altered somehow.  Maybe you added a line, deleted a line, or your editor "helpfully" turned some plain quotes into smart quotes... I don't know what, but something.  42's reading of input files is not robust to these things.  Once it gets out of sync, you get variables being initialized with nonsense, and the crash message you got is one of the common symptoms.  If you are comfortable with a debugger, put a breakpoint where the error message is generated and trace it back.  This will help you figure out which input file got out of line.  (If you're not familiar with a debugger, I highly recommend you get acquainted.  It's a worthwhile investment.)

Regards,
-Eric
